require("cc.set")
require("cc.lazy")
require("cc.autocmds")
require("cc.remap")
require("cc.other")
vim.cmd([[command! -nargs=0 GoToFile :Telescope smart_open]])
vim.cmd([[command! -nargs=0 MiniSessionConfig :lua MiniSessions.read('config')]])
vim.cmd([[command! -nargs=0 MiniSessionVapStConnector :lua MiniSessions.read('vap-st-connector')]])
vim.cmd([[command! -nargs=0 MiniSessionNotes :lua MiniSessions.read('Notes')]])
-- vim.cmd([[command! -nargs=0 GoToFile :Telescope find_files]])
